language: android
android:
  components:

	# The BuildTools version used by your project
    - build-tools-16.1.0
	
	# The SDK version used to compile your project
	- android-16
		
	# Specify at least one system image,
	# if you need to run emulator(s) during your tests
